In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [27]:
# Load the dataset
file_path = 'C:/Users/shiva/OneDrive/Documents/CIBERTECH 1.csv'
iris_data = pd.read_csv(file_path)

In [28]:
iris_data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [29]:
# Drop the 'Id' column
iris_data.drop(columns=['Id'], inplace=True)

In [30]:
# Encode the target variable 'Species'
label_encoder = LabelEncoder()
iris_data['Species'] = label_encoder.fit_transform(iris_data['Species'])

In [31]:
iris_data['Species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

In [32]:
# Split the data into features and target
X = iris_data.drop(columns=['Species'])
y = iris_data['Species']

In [33]:
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [34]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

In [35]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
X_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
22             4.6           3.6            1.0           0.2
15             5.7           4.4            1.5           0.4
65             6.7           3.1            4.4           1.4
11             4.8           3.4            1.6           0.2
42             4.4           3.2            1.3           0.2
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[120 rows x 4 columns]

In [37]:
 X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73             6.1           2.8            4.7           1.2
18             5.7           3.8            1.7           0.3
118            7.7           2.6            6.9           2.3
78             6.0           2.9            4.5           1.5
76             6.8           2.8            4.8           1.4
31             5.4           3.4            1.5           0.4
64             5.6           2.9            3.6           1.3
141            6.9           3.1            5.1           2.3
68             6.2           2.2            4.5           1.5
82             5.8           2.7            3.9           1.2
110            6.5           3.2            5.1           2.0
12             4.8           3.0            1.4           0.1
36             5.5           3.5            1.3           0.2
9              4.9           3.1            1.5           0.1
19             5.1           3.8            1.5           0.3
56             6.3           3.3            4.7           1.6
104            6.5           3.0            5.8           2.2
69             5.6           2.5            3.9           1.1
55             5.7           2.8            4.5           1.3
132            6.4           2.8            5.6           2.2
29             4.7           3.2            1.6           0.2
127            6.1           3.0            4.9           1.8
26             5.0           3.4            1.6           0.4
128            6.4           2.8            5.6           2.1
131            7.9           3.8            6.4           2.0
145            6.7           3.0            5.2           2.3
108            6.7           2.5            5.8           1.8
143            6.8           3.2            5.9           2.3
45             4.8           3.0            1.4           0.3
30             4.8           3.1            1.6           0.2

In [38]:
y_train

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: Species, Length: 120, dtype: int32

In [39]:
y_test

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: Species, dtype: int32

In [40]:
# Train a Decision Tree Classifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [41]:
# Make predictions
y_pred = model.predict(X_test)

In [42]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [43]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
classification_report_result = classification_report(y_test, y_pred)
confusion_matrix_result = confusion_matrix(y_test, y_pred)

In [44]:
print(f'Accuracy: {accuracy}')

Accuracy: 1.0

In [45]:
print('Classification Report:')
print(classification_report_result)

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [46]:
print('Confusion Matrix:')
print(confusion_matrix_result)

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]